site_name: Learn Python Programming Language
# site_url: https://james-willett.github.io/mkdocs-material-youtube-tutorial/
# site_url: https://example.com/
site_url: https://github.com/NitkarshChourasia

nav:
  - Home: README.md
  - Downloads: README.md
  - Music: README.md
  - Assets: README.md
  - About: README.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
# This switch is not appearing, make it good.

# plugins:
# - social

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/NitkarshChourasia
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/NitkarshC
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/willettjames/ # Put mine. Here.
      link: https://www.linkedin.com/in/nitkarshchourasia

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  <!-- &copy; 2023 <a href="https://github.com/james-willett"  target="_blank" rel="noopener">James Willett</a> -->
  &copy; 2023 <a href="https://github.com/NitkarshChourasia"  target="_blank" rel="noopener">Nitkarsh Chourasia</a>

# At the last ask bing how to improve it further.

# Make it fully, and extra loaded.
